### ISSUE TITLE
It seems to have two side effects

### ISSUE THREAD

**Issue by wonu** [tomayac/project-fugu-api-detector#3]
### After activating in Chrome incognito mode, Google search histories are shared in the synced account
I'm using Chrome(110.0.5481.178) and my Google account is synced.
And let the extension be activated in incognito mode.
Then after I search on google.com in incognito tab, I can find the search history on search field of google.com in normal tab like I searched in normal tab.
Other browser histories don't seem to be shared as expected.

### Disturbing OAuth 2.0 flow
Regardless of activation in incognito mode, it disturbs OAuth flow so signing in services like GitHub or Postman fails.

---

I don't know if these are inevitable to work and I'm not even sure the extension is the cause.
So sorry about that if I'm wrong :)

**Comment by tomayac** [comment]
I can assure you this is not due to the extension. You can verify as per the source code, but also via the series of screenshots (note how the extension is active in the extensions section in both incognito and regular mode):

1. About to perform a new search in incognito mode:
   ![Screenshot 2023-02-27 at 10 13 46](https://user-images.githubusercontent.com/145676/221522522-00e133fa-e3d7-413c-be7e-3d4b05769c1e.png)
1. Seeing search results in incognito mode:
   ![Screenshot 2023-02-27 at 10 13 56](https://user-images.githubusercontent.com/145676/221522534-3060536d-6748-459b-bfcf-6edf534f9b18.png)
1. Trying to make autocomplete suggest in my regular profile what I searched in incognito mode:
   ![Screenshot 2023-02-27 at 10 14 36](https://user-images.githubusercontent.com/145676/221522537-aef054d1-a754-4dcb-ace6-5831a5ab6c61.png)

**Comment by wonu** [comment]
Thank you for your kind response.

I should have attached the video, sorry.

Here's my reproduction:

https://user-images.githubusercontent.com/9602236/221627663-fda2b482-9bd6-4d2e-b59f-bb5d6a869521.mp4

\
Please understand that other extensions do not cause this issue, so I have no choice but to leave an issue here even if this extension is not relevant.

I tested on Windows 11 & 10 with different accounts and could see this issue on both.

**Comment by tomayac** [comment]
OK, so technically you are not on Google as in `https://www.google.com/`, but on a special Chrome-internal page with the pseudo URL [`chrome://new-tab-page/`](chrome://new-tab-page/) (a bit outdated [background](https://www.chromium.org/user-experience/new-tab-page/), [source code](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/new_tab_page/)). It seems like this special page (for _you_) populates queries with queries you have run in incognito tabs. I personally still could not reproduce the problem, but this seems to be the reason. I have filed a [Chromium issue](https://crbug.com/1419979) to track the problem. Please go to the bug and click the star ⭐️ icon to be informed of updates.
